---
- hosts: local
  connection: local
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: copy file to destination
      copy:
        src: /tmp/index.html
        dest: /tmp/devops/ansible-practice
        
